### ISSUE TITLE
Os dados da fila não estão sendo enviados

### ISSUE THREAD

**Issue by vitorkalleu** [gunterbr/Painel_de_Chamadas_e-SUS_PEC#1]
Segui as orientações e consegui realizar a instalação.
Porem não esta identificando a fila do do sistema Esus. Consegue sugerir o que eu posso ter feito errado?
![image](https://github.com/gunterbr/Painel_de_Chamadas_e-SUS_PEC/assets/135127194/ba7fe1e3-d882-449e-953c-ebabef268e0e)

**Comment by gunterbr** [comment]
Olá. Que bom que chegou até esta etapa.
**Está tudo certo com sua instalação. Não há nada de errado.**

Agora você precisa do arquivo de **licença** para receber a lista de atendimento diretamente no painel. As instruções de como obter a licença estão neste tutorial que você seguiu.

**Comment by gunterbr** [comment]
Qualquer dúvida, estamos à disposição :)

**Comment by gunterbr** [comment]
Qualquer dúvida, estamos à disposição
