### ISSUE TITLE
Integração com o e-SUS PEC

### ISSUE THREAD

**Issue by andersonsouzabass** [gunterbr/Painel_de_Chamadas_e-SUS_PEC#2]
Há alguma inciativa para integrá-lo ao e-SUS PEC?

**Comment by gunterbr** [comment]
> Há alguma inciativa para integrá-lo ao e-SUS PEC?

Ele já é totalmente integrado em tempo real à base do PEC ;)

**Comment by andersonsouzabass** [comment]
> > Há alguma inciativa para integrá-lo ao e-SUS PEC?
> 
> Ele já é totalmente integrado em tempo real à base do PEC ;)

Que maravilha. Caso encontre alguma dificuldade, você conseguiria nos dar algum apoio na instalação da ferramenta?

**Comment by gunterbr** [comment]
> > > Há alguma inciativa para integrá-lo ao e-SUS PEC?
> > 
> > 
> > Ele já é totalmente integrado em tempo real à base do PEC ;)
> 
> Que maravilha. Caso encontre alguma dificuldade, você conseguiria nos dar algum apoio na instalação da ferramenta?

Sim
